services:
  - type: web
    name: resume-analyzer-backend
    runtime: image
    image:
      url: eclipse-temurin:17-jdk-alpine
    rootDir: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false